name: Build binaries

on:
  release:
    types:
      - created

jobs:
  binaries:
    name: Cross-platform builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.1.0
        with:
          platforms: linux/amd64,linux/arm64
          name: freeswitch_exporter
          dest: dist

      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./dist/*
